### ISSUE TITLE
How to build/install ?

### ISSUE THREAD

**Issue by Koala-gentil** [brandizzi/input-device-indicator#9]
I'm using Ubuntu 18.04.
I saw there is a PPA in Makefile so I tried this :
```
sudo add-apt-repository ppa:brandizzi/ppa
sudo apt-get update 
sudo apt-get install input-device-indicator
```

But when I run input-device-indicator I have this error :
```
Traceback (most recent call last):
  File "/usr/bin/input-device-indicator", line 11, in <module>
    load_entry_point('input-device-indicator==0.1.0', 'gui_scripts', 'input-device-indicator')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/inputdeviceindicator/main.py", line 20, in <module>
    gi.require_version('AppIndicator3', '0.1')  # noqa
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

**Comment by Koala-gentil** [comment]
This solved my problem :
```
sudo apt-get install gir1.2-appindicator3-0.1
```

This should be documented.

Anyway, me and my cat thanks you for this tool ! :cat2:

**Comment by brandizzi** [comment]
Version 0.1.1 should have this issue fixed.
